server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://101.43.18.117:3306/db_example?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: xq
    password: xq123!

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml